version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: helm-github-pages
          environment:
            - GITHUB_PAGES_REPO: cristi0204/nifi-helm
            - HELM_CHART: nifi
            - HELM_VERSION: 3.9.0
          command: wget -O - https://raw.githubusercontent.com/cristi0204/helm-github-pages/master/publish.sh | sh
